# WARNING: This docker-compose.yml is only for testing purpose.
# Parameters:
# - name: KAFKA_VERSION
#   default: latest
#   reference: https://hub.docker.com/u/confluentinc/
# Ports:
# - description: Multiple kafka broker with a singular zookeeper, and a kafka manager on top, the kafka manager is initialized
#                with the cluster details running as services here. In case a name isn't pr√≥vided at the start the cluster will 
#                be named as testing.
# - zookeeper: 2181
#      kafka: 9092, 9093, 9094
version: "3.7"
services:
  zookeeper:
    image: zookeeper:${KAFKA_VERSION:-latest}
    hostname: zookeeper
    container_name: zookeeper
    build:
      context: ../../../images/zookeeper
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SERVER_ID:  1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    volumes:
      - zk-data:/opt/zookeeper/data
      - zk-logs:/opt/zookeeper/log
    networks:
      - kafka-net

  kafka1:
    image: kafka-broker:${KAFKA_VERSION:-latest}
    hostname: kafka1
    container_name: kafka1
    build:
      context: ../../../images/kafka-broker
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_LOG_RETENTION_HOURS: 12
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 3600000
      KAFKA_PORT: 9092
    restart: always
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafka2:
      image: kafka-broker:${KAFKA_VERSION:-latest}
      hostname: kafka2
      container_name: kafka2
      build:
        context: ../../../images/kafka-broker
        dockerfile: Dockerfile
      ports:
        - "9093:9093"
        - "29093:29093"
      environment:
        KAFKA_BROKER_ID: 2
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:29093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
        KAFKA_LOG_RETENTION_HOURS: 12
        KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 3600000
        KAFKA_PORT: 9093
      restart: always
      depends_on:
        - zookeeper
      networks:
        - kafka-net

  kafka3:
      image: kafka-broker:${KAFKA_VERSION:-latest}
      hostname: kafka3
      container_name: kafka3
      build:
        context: ../../../images/kafka-broker
        dockerfile: Dockerfile
      ports:
        - "9094:9094"
        - "29094:29094"
      environment:
        KAFKA_BROKER_ID: 3
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:29094,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
        KAFKA_LOG_RETENTION_HOURS: 12
        KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 3600000
        KAFKA_PORT: 9094
      restart: always
      depends_on:
        - zookeeper
      networks:
        - kafka-net 
        
  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    hostname: kafka-manager
    container_name: kafka-manager
    depends_on:
      - kafka
      - zookeeper
    command: -Dconfig.file=/kafka-manager/conf/application.conf -Dapplication.home=/kafkamanager
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: randomSecret
    networks:
      - kafka-net
    ports:
      - "9000:9000"

  manager-cluster-init:
    image: ellerbrock/alpine-bash-curl-ssl
    restart: "no"
    container_name: init
    environment:
      KAFKA_MANAGER_HOST: kafka-manager:9000
      KAFKA_CLUSTER_NAME: ${KAFKA_CLUSTER_NAME:-testing}
      KAFKA_VERSION: ${KAFKA_VERSION:-2.4.0}
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - kafka-manager
      - kafka
      - zookeeper
    networks:
      - kafka-net
    command: /bin/bash /kafka-cluster-init.sh
    volumes:
      - "./kafka-cluster-init.sh:/kafka-cluster-init.sh"

volumes:
  zk-data:
  zk-logs:

networks:
  kafka-net:
    name: kafka-net
    driver: bridge
